name: ci and review

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REVIEW_URL: ecordel-review-${{ github.event.pull_request.number }}.surge.sh
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build
        env: 
          REACT_APP_API_URL: ${{secrets.API_DEV}}
      - name: Deploy to review environment
        run: |      
          echo https://${{ env.REVIEW_URL }}
          npx surge --project ./build --domain ecordel-review-${{ github.event.pull_request.number }}.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Review URL https://${{ env.REVIEW_URL }}'
            })
