name: ci and review

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build
        env: 
          REACT_APP_API_URL: ${{secrets.API_DEV}}
