name: ci and app review

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
      - name: Build
        run: yarn build
        env: 
          REACT_APP_API_URL: ${{secrets.API_DEV}}
      - shell: bash
        run: |
          tar -zcf dist.tar.gz ./build/
      - name: Upload cordel-web artifact
        uses: actions/upload-artifact@v2
        with:
          name: ecordel-web
          path: dist.tar.gz
      
      - name: Deploy to Review environment
        if: github.event_name =='pull_request'
        run: |      
          echo ecordel-review-${{ github.event.pull_request.number }}.surge.sh
          npx surge --project ./build --domain ecordel-review-${{ github.event.pull_request.number }}.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}