name: merge-develop-into-master

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge development -> master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: develop
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
